version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies needed."

  build:
    commands:
      - echo "Build started on $(date)"

  post_build:
    commands:
      - echo "Deploying to S3..."
      - aws s3 sync . s3://pb-exp-8-devops --delete
